//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bulls_Allowed_to_Booze.WebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUID", ReplyAction="http://tempuri.org/IService1/RegisterUIDResponse")]
        bool RegisterUID(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUID", ReplyAction="http://tempuri.org/IService1/RegisterUIDResponse")]
        System.Threading.Tasks.Task<bool> RegisterUIDAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerifyUID", ReplyAction="http://tempuri.org/IService1/VerifyUIDResponse")]
        bool VerifyUID(string id, bool isverified, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerifyUID", ReplyAction="http://tempuri.org/IService1/VerifyUIDResponse")]
        System.Threading.Tasks.Task<bool> VerifyUIDAsync(string id, bool isverified, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUID", ReplyAction="http://tempuri.org/IService1/CheckUIDResponse")]
        string CheckUID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUID", ReplyAction="http://tempuri.org/IService1/CheckUIDResponse")]
        System.Threading.Tasks.Task<string> CheckUIDAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Bulls_Allowed_to_Booze.WebServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Bulls_Allowed_to_Booze.WebServiceReference.IService1>, Bulls_Allowed_to_Booze.WebServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUID(string value) {
            return base.Channel.RegisterUID(value);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUIDAsync(string value) {
            return base.Channel.RegisterUIDAsync(value);
        }
        
        public bool VerifyUID(string id, bool isverified, string comment) {
            return base.Channel.VerifyUID(id, isverified, comment);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyUIDAsync(string id, bool isverified, string comment) {
            return base.Channel.VerifyUIDAsync(id, isverified, comment);
        }
        
        public string CheckUID(string id) {
            return base.Channel.CheckUID(id);
        }
        
        public System.Threading.Tasks.Task<string> CheckUIDAsync(string id) {
            return base.Channel.CheckUIDAsync(id);
        }
    }
}
